from typing import Protocol, Optional, List
from .room import Room
from .booking import Booking


class RoomRepository(Protocol):
    def get(self, room_id: int) -> Optional[Room]: ...
    def save(self, room: Room) -> None: ...


class BookingRepository(Protocol):
    def get(self, booking_id: int) -> Optional[Booking]: ...
    def save(self, booking: Booking) -> None: ...
    def list_by_room(self, room_id: int) -> List[Booking]: ...